name: rickyfrancisco
favicon: null
layout_spectrum: 0.3398033883422613
typography_spectrum: 0.2661609204951674
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6192105356603861
  lightness: 0.74614934832789
  saturation: 0.38021817430853844
  rhythmicContrast: 0.6619732910767198
purpose: []
